cache:
  paths:
    - .cache/pip
    - venv/

services:
  - docker:dind

variables:
    POSTGRES_PASSWORD: 1234
    DOCKER_TLS_CERTDIR: ""
    RMQ_HOST: rabbitmq
    DB_HOST: postgres
    API: "563492ad6f917000010000011bc9ae20b2ea4640873fdd836c929c8b"

stages:
    - test
    - go_docker_hub

# before_script:
#   - python -V  # Print out python version for debugging
#   - pip install virtualenv
#   - virtualenv venv
#   - source venv/bin/activate

test:
    image: python:3.8.2-alpine
    services:
        - postgres:12.2-alpine
        - rabbitmq:alpine
    stage: test
    script:
    - apk update && apk add --no-cache python3-dev pytest postgresql-dev musl-dev docker git
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install -r requirements.txt --user
    - cd test
    - pytest



go_docker_hub:
    image: docker
    stage: go_docker_hub
    script:
    - docker login -u kz159 -p $DOCKER_PASS
    - docker build -t walld_grab_pexels .
    - docker tag walld_grab_pexels kz159/walld_grab_pexels
    - docker push kz159/walld_grab_pexels
