variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


variables:
    POSTGRES_PASSWORD: 1234
    DOCKER_TLS_CERTDIR: ""


stages:
    - test
    - go_docker_hub

# before_script:
#   - python -V  # Print out python version for debugging
#   - pip install virtualenv
#   - virtualenv venv
#   - source venv/bin/activate

test:
    image: python:3.8.2-alpine
    services:
        - postgres:12.2-alpine
    stage: test
    script:
    - export DB_HOST=postgres
    - apk update && apk add --no-cache python-dev pytest docker
    - pip install -r requirements.txt
    - pytest test/test1.py
    
go_docker_hub:
    image: docker
    stage: go_docker_hub
    services:
      - docker:dind
    script:
    - docker build -t walld_grab_pexels .
    - docker tag walld_grab_pexels kz159/walld_grab_pexels
    - docker push kz159/walld_grab_pexels

