image: python:3.8.2-alpine

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

services:
    - postgres:12.2-alpine

variables:
    POSTGRES_PASSWORD: 1234

stages:
    - test
    - go_docker_hub

test:
    stage: test
    script:
    - export DB_HOST=postgres
    - apk update && apk add --no-cache python-dev pytest docker
    - pip install -r requirements.txt
    - pytest
    
go_docker_hub:
    stage: go_docker_hub
    docker build -t walld_grab_pexels .
    docker tag walld_grab_pexels kz159/walld_grab_pexels
    docker push kz159/walld_grab_pexels

